openapi: 3.0.0
info:
  title: PrimeEvent REST API Services
  version: '1.0'
servers:
- url: localhost:8085
  description: localhost
  variables: {}
tags:
- name: PrimeEventService
security:
- BasicAuth: []
paths:
  /primeevent/events:
    post:
      tags:
      - PrimeEventService
      summary: notifyEvent
      description: Notify occurance of PrimeOnline event
      operationId: notifyEvent
      parameters:
      - name: Accept
        in: header
        description: Specifies the accepted media type of the response and the requested version of the service.
        required: true
        schema:
          type: string
          enum:
              - application/vnd.sparebank1.v1+json; charset=utf-8
      - name: X-REQUEST-ID
        in: header
        description: A traceable request UUID. If this request is initiated by an incoming request, then reuse the incoming request id. Or else create a new UUID for the request.
        required: true
        schema:
          type: string
          example: ac12eccf-97a8-442f-9b48-a6e2cc91e7a2
      - name: X-APPLICATION-NAME
        in: header
        description: Application name of client consuming the service.
        required: true
        schema:
          type: string
          example: ntf_services
      - name: X-USER-ID
        in: header
        description: The user id associated with the request. In self service channels the SSN of the customer, or else the office user id or system id.
        required: true
        schema:
          type: string
      - name: X-BANK-NUMBER
        in: header
        description: The 4-digit bank number to be associated with the request. Consumer identifies which kind of financial institution by passing either X-BANK-NUMBER or X-ORG-NUMBER, not both.
        schema:
          type: string
          example: "4201" 
      - name: X-ORG-NUMBER
        in: header
        description: The 9-digit organization number to be associated with the request. Consumer identifies which kind of financial institution by passing either X-BANK-NUMBER or X-ORG-NUMBER, not both.
        schema:
          type: string
          example: "987654321"             
      - name: X-CUSTOMER-SSN
        in: header
        required: true
        schema:
          type: string
          description: The customer SSN associated with the request, identifying a private person.
          example: "05069012345"          
      requestBody:
        description: Data for notify event
        content:
          application/vnd.sparebank1.v1+json; charset=utf-8:
            schema:
              $ref: '#/components/schemas/Event'
        required: true
      responses:
        201:
          description: Created Successfully
        400:
          description: Bad Request
          content:
            application/vnd.sparebank1.v1+json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/RestError'          
        401:
          description: Unauthorized
          content:
            application/vnd.sparebank1.v1+json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/RestError'          
        500:
          description: Server side error
          content:
            application/vnd.sparebank1.v1+json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/RestError'
components:
  schemas:
    Event:
      required:
      - type
      type: object
      properties:
        type:
          type: string
          description: Prime Event Type.
          example: NEW_ACCOUNT      
        details:
          minItems: 0
          type: array
          description: Optional user specified name/value pairs provided with the event notification
          items:
            type: object
            properties:
              dataType:
                $ref: '#/components/schemas/DataType'
              name:
                type: string
                description: Prime Event name.
                example: accountSerno
              value:
                type: string
                description: Prime Event value.
                example: "123456"
            description: POJO that represents a KeyValue.
      description: POJO that represents a PrimeOnline event.
    RestError:
      required:
      - code
      type: object
      properties:
        statusCode:
          type: integer
          description: Error code.
          example: 400     
        errorCode:
          type: string
          description: Error code.
          example: INVALID_DATATYPE  
        errorMessage:
          type: string
          description: Error message.
          example: Datatype NUMERIC is not a valid for value ABCD      
      description: POJO that represents a REST Error.      
    DataType:
      type: string
      description: Data type defines the values that a variable can take, for example
        if a variable has 'NUMERIC' data type, it can only take numbers as values.
      enum:
      - NUMERIC
      - TEXT
      - DATE
      - DECIMAL
      - TEXT_ARRAY
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
